POOII_EF_RamosLucas/Models/ErrorViewModel.cs
namespace POOII_EF_RamosLucas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

POOII_EF_RamosLucas/Models/Seminario.cs
using System.ComponentModel;

namespace POOII_EF_RamosLucas.Models
{
    public class Seminario
    {
        [DisplayName("Codigo de Seminario")]
        public int CodigoSeminario { get; set; }

        [DisplayName("Nombre del Curso")]
        public string NombreCurso { get; set; }

        [DisplayName("Horario de Clase")]
        public string HorarioClase { get; set; }

        [DisplayName("Capacidad")]
        public int Capacidad { get; set; }
    }
}

POOII_EF_RamosLucas/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using POOII_EF_RamosLucas.Models;

namespace POOII_EF_RamosLucas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

POOII_EF_RamosLucas/Controllers/SeminarioController.cs
using Microsoft.AspNetCore.Mvc;
using POOII_EF_RamosLucas.Data;

namespace POOII_EF_RamosLucas.Controllers
{
    public class SeminarioController : Controller
    {
        private readonly SeminarioDAO _dao;

        public SeminarioController(SeminarioDAO dao)
        {
            _dao = dao;
        }
       
        public IActionResult Index()
        {
            return View(_dao.ListarDisponibles());
        }

      
        public IActionResult Detalle(int id)
        {
            return View(_dao.ObtenerPorCodigo(id));
        }
      
        [HttpPost]
        public IActionResult Registrar(int codigoSeminario, int codigoEstudiante)
        {
            int nroRegistro = _dao.RegistrarAsistencia(codigoSeminario, codigoEstudiante);
            TempData["Mensaje"] = "Registro exitoso. N° Registro: " + nroRegistro;
            return RedirectToAction("Index");
        }
    }
}

POOII_EF_RamosLucas/Views/Seminario/Detalle.cshtml
@model POOII_EF_RamosLucas.Models.Seminario

@{
    ViewData["Title"] = "Detalle";
}

<h1>Detalle</h1>

<div>
    <h4>Seminario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoSeminario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoSeminario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCurso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCurso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HorarioClase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HorarioClase)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacidad)
        </dd>
    </dl>
</div>


<h2>Registrar Asistencia</h2>

<form method="post" asp-action="Registrar" asp-controller="Seminario">
    <div class="input-group mb-3">
        <input id="CodigoEstudiante" name="CodigoEstudiante" type="text" class="form-control" placeholder="Codigo de Estudiante" aria-label="Codigo de Estudiante">
        <input type="hidden" asp-for="CodigoSeminario" />
    </div>

    <button type="submit" class="btn btn-primary mb-3">Enviar</button>

</form>
<div>
    <a class="btn btn-secondary" asp-action="Index">Regresar</a>
</div>

POOII_EF_RamosLucas/Views/Seminario/Index.cshtml
@model List<Seminario>
<h2>Seminarios Disponibles</h2>

@if (TempData["Mensaje"] != null)
{
    <p style="color:green">@TempData["Mensaje"]</p>
}

<table border="1">
    <tr>
        <th>Curso</th>
        <th>Horario</th>
        <th>Capacidad</th>
        <th></th>
    </tr>
    @foreach (var s in Model) 
    {
        <tr>
            <td>@s.NombreCurso</td>
            <td>@s.HorarioClase</td>
            <td>@s.Capacidad</td>
            <td>
                <a asp-action="Detalle" asp-route-id="@s.CodigoSeminario">
                    Seleccionar
                </a>
            </td>
        </tr>
    }
</table>


@{
    ViewData["Title"] = "Home Page";
}

POOII_EF_RamosLucas/Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - POOII_EF_RamosLucas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/POOII_EF_RamosLucas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">POOII_EF_RamosLucas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - POOII_EF_RamosLucas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>